apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ml
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: ap-southeast-1
type: Opaque
# stringData section containing AWS keys is completely removed
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: ml
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::704048935372:role/kserve-serviceaccount-role-fullaccess
secrets:
  - name: s3-secret